### ISSUE TITLE
No title attribute in links

### ISSUE THREAD

**Issue by dragonito** [tolry/talkly#105]
There are no title attributes in links when hoovering the first two buttons.
![2016-11-24 11_53_47-talkly](https://cloud.githubusercontent.com/assets/1980412/20596060/ece4316c-b23c-11e6-8ad0-0a4055f3a436.png)

**Comment by tolry** [comment]
👍

**Comment by DavidBadura** [comment]
@dragonito don't you want to create a PR? :smiley:

**Comment by dragonito** [comment]
Could you name the Icons?

**Comment by tolry** [comment]
suggestions

* first button "finalize talk"
* second button "edit talk"

**Comment by DavidBadura** [comment]
@dragonito ping ;-)

**Comment by dragonito** [comment]
Done please check
