### ISSUE TITLE
Lecture date should be revocable

### ISSUE THREAD

**Issue by smoench** [tolry/talkly#50]
<code>
FatalErrorException: Error: Call to a member function format() on a non-object in ******/src/TobiasOlry/Talkly/Event/Subscriber/NotificationSubscriber.php line 102
</code>

**Comment by tolry** [comment]
Thanks for the report. Will you fix this or should I take a look at it?

**Comment by smoench** [comment]
I will fix it

**Comment by tolry** [comment]
great, thx
