### ISSUE TITLE
revert angularJs changes

### ISSUE THREAD

**Issue by DavidBadura** [tolry/talkly#60]
since adding angularJs, some things do not work anymore. for example flash messages, scrolling to thopic and display next talks. none of us can or have time to learn angularJs, so i think we should revert it.

**Comment by DavidBadura** [comment]
see #55

**Comment by tolry** [comment]
I am not totally happy with the current state myself. Development has come to a halt due to the lack of Anuglar.JS - but I would like to give @smoench the chance to defend his work. Any thoughts on this?

@DavidBadura let's talk about those "flash massages" later :wink:

**Comment by tolry** [comment]
Since we are already at a point of no return with migrating to react (see #70), I am closing this.
