### ISSUE TITLE
talk sorting

### ISSUE THREAD

**Issue by SophieAnn** [tolry/talkly#61]
I think it makes more sense, if the talks with a date are the first one of the list. Every time I create a new one, I don't know which dates are free or which talk is next. I liked the coming dates list on the left side before.

**Comment by tolry** [comment]
Agreed, the current situation is not optimal. This is directly related to #60 - as I see it, arguments for reverting those changes are growing.

Any thoughts @smoench @DavidBadura ?

**Comment by DavidBadura** [comment]
i think we can close this because of #62 ?

**Comment by tolry** [comment]
right and the topic list will be redesigned completely when switching to react
