### ISSUE TITLE
forms not submitted due to markdown preview rendering

### ISSUE THREAD

**Issue by tolry** [tolry/talkly#66]
When hitting the submit button while still having focus on a textarea with markdown preview, the form will not be submitted, the button needs to be activated a second time.

Probable reason: when leaving the focus of the textarea, an update of the markdown preview is triggered, probably returning false at the end, preventing event flow from continuing.

It would although probably be best for the markdown preview, if it would only update on (real/relevant) changes in the textarea.

**Comment by DavidBadura** [comment]
see #70
